# -*- coding: utf-8 -*-
"""LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1786Etg9UMfPniMS9UtyJG-vVAn-b4gno

Objective:

The LLM generates the output from the collected data, text.

Application:

Analyzing research papers and cathegorizes it.
"""

# restart the kernel if necessary
from IPython.display import Javascript
Javascript('IPython.notebook.kernel.restart();')
#settings
!pip install matplotlib-venn
!pip install opendatasets datasets accelerate --quiet
import opendatasets as od

"""Workflow of the LLM:
- Loading data
- Cleaning data
- Preprocessing data
- Building Dataset/DataPipe
- Building DataLoaders
- Building Model
- Defining Loss Function
- Defining Optimizer
- Training Loop
- Predictions/Evaluation
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile myspider.py
# 
# import scrapy
# 
# class BlogSpider(scrapy.Spider):
#     name = 'blogspider'
#     search_topic = 'neurology'
#     base_url = 'https://pubmed.ncbi.nlm.nih.gov'
#     start_urls = [ base_url + '/?term=' + search_topic ]
#     page = 1
# 
# 
#     def parse(self, response):
#         for title in response.css('.docsum-title'):
#             doc_url = self.base_url + title.css("a::attr(href)").get()
#             yield scrapy.Request(url=doc_url, callback=self.parse_doc)
# 
#         while self.page < int(response.css('.page-number').attrib["max"]):
#             self.page += 1
#             next_url = self.start_urls[0] + '&page=' + str(self.page)
#             yield response.follow(next_url, self.parse)
# 
#     def parse_doc(self, response):
#         for text in response.css('.abstract p::text').getall():
#             yield { 'abstract': text }
# 
# doc_url = self.base_url + title.css("a::attr(href)").get()

#!pip install --upgrade ipython
#!pip install jupyterlab-celltags
#!jupyter labextension install @jupyterlab/celltags
#!jupyter lab build

# Collect data with Scrapy, for now only from PubMed, key word: neurology
!pip install scrapy
!cat > myspider.py <<EOF
!pip show ipython
#%%writefile myspider.py  it does not work for some reason...
import scrapy

# Write the spider code to 'myspider.py'
with open('myspider.py', 'w') as f:
    f.write('''
import scrapy

class BlogSpider(scrapy.Spider):
    name = 'blogspider'
    start_urls = ['https://pubmed.ncbi.nlm.nih.gov/']

    def parse(self, response):
        for title in response.css('.neurology'):
            yield {'title': title.css('::text').get()}

        for next_page in response.css('a.next'):
            yield response.follow(next_page, self.parse)
    ''')

# Now you can run the spider
!scrapy runspider myspider.py -o output.json



#Filter the text
#Filter function
import re
import pandas as pd
import random


#split up the file!!!, 2-3 Gb max.
#in different training loop


#def clean_text(text):
#  text = text.lower()
#  text = re.sub(r'[^A-Za-z0-9]+', ' ', text) # Use parentheses for the regex pattern
#  return text


#Filter the Python file
#it opens a text file
# Convert the text file to a processable format, because str does not have attribute samlpe
#with open('/content/test_LLM.py', 'r') as f:
#  content = f.read()
#  cleaned_content = clean_text(content) # Apply the cleaning function
#  print(cleaned_content)

#n = 5  # Sample every 5th line
#systematic_sample = lines[::n]
#print(systematic_sample)


data = pd.read_csv('/content/ntrarogyaseva.csv')
data.head()

#split the data for training, validation and verification dataset

#validation vs verification
#train, test
import pandas as pd
data = pd.read_csv('/content/ntrarogyaseva.csv')
train = data.sample(frac = 0.7)
test = data.drop(train.index)

#validation
val = data.sample(frac = 0.7)
test = data.drop(val.index)

print("Training Shape:", train.shape)
print("Validation Shape:", val.shape)
print("Testing Shape:", test.shape)

#Tokenizing, supervised learning involved
#!pip install datasets==2.11.0
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from datasets import load_dataset

# Load dataset
dataset = load_dataset('/content/ntrarogyaseva.csv')

# Load pre-trained tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

# Tokenize data
def tokenize_function(examples):
    return tokenizer(examples['text'], padding='max_length', truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
)

# Define Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['test'],
)

# Train model
trainer.train()

#unsupervised learning: categorizing the articles, make predictions about the future
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# Load dataset
articles = load_dataset()  # Assuming a function that loads your dataset of articles

# Preprocess and convert to TF-IDF features
vectorizer = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')
tfidf_matrix = vectorizer.fit_transform(articles)

# Apply LDA for topic modeling
lda = LatentDirichletAllocation(n_components=5, random_state=42)  # 5 topics
lda.fit(tfidf_matrix)

# Display top words for each topic
n_top_words = 10
feature_names = vectorizer.get_feature_names_out()
for topic_idx, topic in enumerate(lda.components_):
    print(f'Topic #{topic_idx}:')
    print(' '.join([feature_names[i] for i in topic.argsort()[:-n_top_words - 1:-1]]))

#Training
#Split the dataset into training and testing set
#Initialize loss function
#Select number of epochs (the number of trining iterations through the network)
#Run the training loop for that number of epochs

#pretraining, finetuning



#"Statistics", for example accuracy, F1, precision etc.